const fs = require("fs");
const Schema = require("./employees_pb");
const ritvik = new Schema.Employee();
ritvik.setId(100);
ritvik.setName("Rakesh");
ritvik.setSalary(20000);
const ramesh = new Schema.Employee();
ramesh.setId(11200);
ramesh.setName("Rakesh");
ramesh.setSalary(20222);
const employees = new Schema.Employees();
employees.addEmployees(ritvik);
employees.addEmployees(ramesh);
console.log(employees);
console.log("binary: " + employees.serializeBinary());
fs.writeFileSync("./binaryData", employees.serializeBinary());
const buffer = fs.readFileSync("./binaryData");
const employees2 = Schema.Employees.deserializeBinary(buffer);
console.log(employees2);
